[workspace]
members = [".", "migration", "entities"]

[package]
name = "hubbitos-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
migration = { path = "migration" }
entities = { path = "entities" }
dotenvy = "0.15.7"
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono", "with-json", "with-uuid" ] }
tokio = { version = "1", features = ["full"] }
serde = "1.0.195"
uuid = {version = "1.6.1", features = ["v4"]}
chrono = {version = "0.4.31", features = ["clock"]}
config = "0.13.4"
serde-envfile = "0.1.0"
once_cell = "1.19.0"
validator = { version = "0.15", features = ["derive"] }
jsonwebtoken = "9.2.0"
http = "1.0.0"
scrypt = "0.11.0"
password-auth = "1.0.0"