[workspace]
members = [".", "migration", "entities", "test", "cli"]

[package]
name = "hubbitos_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
migration = { path = "migration" }
entities = { path = "entities" }
hubbitos-cli = { path = "cli" }
dotenvy = "0.15.7"
sea-orm = { version = "0.12", features = [ "sqlx-postgres", "runtime-tokio-rustls", "macros", "chrono", "with-json", "with-uuid" ] }
tokio = { version = "1", features = ["full"] }
serde = "1.0.195"
uuid = {version = "1.6.1", features = ["v4"]}
chrono = {version = "0.4.31", features = ["clock"]}
config = "0.13.4"
serde-envfile = "0.1.0"
once_cell = "1.19.0"
validator = { version = "0.15", features = ["derive"] }
jsonwebtoken = "9.2.0"
http = "1.0.0"
scrypt = "0.11.0"
password-auth = "1.0.0"
cargo-watch = "8.5.2"
async-trait = "0.1.77"
regex = "1.10.3"
unicode-normalization = "0.1.22"
log = "0.4.20"
env_logger = "0.11.1"
duplicate = "1.0.0"

[dev-dependencies]
mockall = "0.12.1"
