version: '3.8'

services:
  postgres:
    container_name: rust-clean-postgres
    mem_limit: "512mb"
    mem_reservation: "512mb"
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: rust-clean
    